pipeline{
    agent any

    stages{
        stage('init'){
            steps{
                sh 'terraform init -reconfigure -no-color'
            }
        }
        stage('validate'){
            steps{
                sh 'terraform validate -no-color'
            }
        }
        stage('format'){
            steps{
                sh 'terraform fmt -no-color'
            }
        }
        stage('plan'){
            steps{
                sh 'terraform plan -lock=false
                  -var "ENVIRONMENT=main" \
                 -var "INSTANCE_TYPE=t2.micro" \
                 -var "REGION=us-east-1" \ -no-color'
            }
        }
    }
}